# Generated by Django 6.1.2 on 2026-10-10 15:57

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='articles/covers/', validators=[core.validators.validate_uploaded_image], verbose_name='Обложка'),
        ),
    ]
