# Generated by Django 6.1.2 on 2026-10-10 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_cover_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationrecord',
            name='decision',
            field=models.CharField(choices=[('published', 'Опубликовано'), ('rejected', 'Отклонено'), ('unpublished', 'Снято с публикации')], max_length=20, verbose_name='Решение'),
        ),
        migrations.AlterField(
            model_name='moderationrecord',
            name='moderator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderation_records', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор решения'),
        ),
    ]
