# Generated by Django 6.1.2 on 2026-10-10 15:57

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_identity_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/', validators=[core.validators.validate_uploaded_image], verbose_name='Аватар'),
        ),
    ]
